# Generated by Django 2.2.1 on 2019-05-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('deposit', models.IntegerField(default=0)),
                ('withdraw', models.IntegerField(default=0)),
            ],
        ),
    ]
