# Generated by Django 2.2.1 on 2019-05-30 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='input_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
