# Generated by Django 2.2.1 on 2019-05-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_money_input_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='input_date',
            field=models.DateTimeField(default=0),
        ),
    ]
