# Generated by Django 2.2.1 on 2019-05-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_auto_20190530_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='input_date',
            field=models.DateTimeField(default=None),
        ),
    ]
